services:
  # PHP-FPM
  php-fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: store-project-php-fpm
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    networks:
      - store-network
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: store_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  # Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: store-project-nginx
    depends_on:
      - php-fpm
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - store-network

  # MySQL
  db:
    image: mysql:8.0
    container_name: store-project-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - store-network

networks:
  store-network:
    driver: bridge

volumes:
  db_data:

